CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL,
    crypto VARCHAR(10) NOT NULL,
    transaction_type VARCHAR(4) NOT NULL,
    amount DECIMAL(20, 8) NOT NULL,
    price_per_unit DECIMAL(20, 2) NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_transactions_portfolio FOREIGN KEY (portfolio_id) REFERENCES portfolios (id) ON DELETE CASCADE,
    CONSTRAINT chk_transactions_type CHECK (transaction_type IN ('BUY', 'SELL'))
);

CREATE INDEX idx_transactions_portfolio_id ON transactions (portfolio_id);
CREATE INDEX idx_transactions_timestamp ON transactions (timestamp DESC);
